# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ezdelivery' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for ezdelivery
  platform :ios, '9.0'
  pod 'Firebase/Core', '~> 5.11.0'
  pod 'Firebase/Auth', '~> 5.11.0'
  pod 'GoogleSignIn'
  
  target 'ezdeliveryTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'ezdelivery-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for ezdelivery-tvOS

  target 'ezdelivery-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
